[package]
name = "wiglrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.2"
bevy_rapier2d = "0.22.0"
tch = { version = "0.13.0" }

[profile.dev.package."*"]
opt-level = 3
